
# vector
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type vector --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type vector --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --results-root results_train

# Hybrid (RSF)
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 2 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 4 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 6 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 8 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 2 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 4 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 6 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 8 --discover-text-score-weight 10 --results-root results_train

python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 2 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 4 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 6 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 8 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 10 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 2 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 4 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 6 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 8 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RSF --discover-vector-score-weight 10 --discover-text-score-weight 10 --results-root results_train

# hybrid (RRF)
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 1 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 2 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 3 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 4 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 1 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 2 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 3 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 4 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 5 --discover-text-rank-penalty 5 --results-root results_train

python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 1 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 2 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 3 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode unified --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 4 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 1 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 2 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 3 --discover-text-rank-penalty 5 --results-root results_train
python scripts/run_hybrid_search_evaluation.py --connection-string phoenix520030.dev3sub2phx.databasede3phx.oraclevcn.com:1527/cdb1_pdb1.regress.rdbms.dev.us.oracle.com --mode parallel --search-type hybrid --discover-k 15 --discover-score-threshold 0.6 --single-user-mode --discover-search-scorer RRF --discover-vector-rank-penalty 4 --discover-text-rank-penalty 5 --results-root results_train


