-- Oracle DDL for formula_1.sqlite
-- Converted from SQLite schema

CREATE TABLE circuits
(
    circuitId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    circuitRef VARCHAR2(4000) DEFAULT '' NOT NULL,
    "name" VARCHAR2(4000) DEFAULT '' NOT NULL,
    "location" VARCHAR2(4000),
    country VARCHAR2(4000),
    lat NUMBER,
    lng NUMBER,
    alt NUMBER,
    url VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    PRIMARY KEY (circuitId)
);

CREATE TABLE constructorResults
(
    constructorResultsId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    points NUMBER,
    "status" VARCHAR2(4000),
    PRIMARY KEY (constructorResultsId),
    FOREIGN KEY (raceId) REFERENCES races (raceId),
    FOREIGN KEY (constructorId) REFERENCES constructors (constructorId)
);

CREATE TABLE constructorStandings
(
    constructorStandingsId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    points NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    positionText VARCHAR2(4000),
    wins NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (constructorStandingsId),
    FOREIGN KEY (raceId) REFERENCES races (raceId),
    FOREIGN KEY (constructorId) REFERENCES constructors (constructorId)
);

CREATE TABLE constructors
(
    constructorId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    constructorRef VARCHAR2(4000) DEFAULT '' NOT NULL,
    "name" VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    nationality VARCHAR2(4000),
    url VARCHAR2(4000) DEFAULT '' NOT NULL,
    PRIMARY KEY (constructorId)
);

CREATE TABLE driverStandings
(
    driverStandingsId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    driverId NUMBER DEFAULT 0 NOT NULL,
    points NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    positionText VARCHAR2(4000),
    wins NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (driverStandingsId),
    FOREIGN KEY (raceId) REFERENCES races (raceId),
    FOREIGN KEY (driverId) REFERENCES drivers (driverId)
);

CREATE TABLE drivers
(
    driverId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    driverRef VARCHAR2(4000) DEFAULT '' NOT NULL,
    "number" NUMBER,
    code VARCHAR2(4000),
    forename VARCHAR2(4000) DEFAULT '' NOT NULL,
    surname VARCHAR2(4000) DEFAULT '' NOT NULL,
    dob DATE,
    nationality VARCHAR2(4000),
    url VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    PRIMARY KEY (driverId)
);

CREATE TABLE lapTimes
(
    raceId NUMBER NOT NULL,
    driverId NUMBER NOT NULL,
    lap NUMBER NOT NULL,
    "position" NUMBER,
    "time" VARCHAR2(4000),
    milliseconds NUMBER,
    PRIMARY KEY (raceId, driverId, lap),
    FOREIGN KEY (raceId) REFERENCES races (raceId),
    FOREIGN KEY (driverId) REFERENCES drivers (driverId)
);

CREATE TABLE pitStops
(
    raceId NUMBER NOT NULL,
    driverId NUMBER NOT NULL,
    "stop" NUMBER NOT NULL,
    lap NUMBER NOT NULL,
    "time" VARCHAR2(4000) NOT NULL,
    duration VARCHAR2(4000),
    milliseconds NUMBER,
    PRIMARY KEY (raceId, driverId, "stop"),
    FOREIGN KEY (raceId) REFERENCES races (raceId),
    FOREIGN KEY (driverId) REFERENCES drivers (driverId)
);

CREATE TABLE qualifying
(
    qualifyId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    driverId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    "number" NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    q1 VARCHAR2(4000),
    q2 VARCHAR2(4000),
    q3 VARCHAR2(4000),
    PRIMARY KEY (qualifyId),
    FOREIGN KEY (raceId) REFERENCES races (raceId),
    FOREIGN KEY (driverId) REFERENCES drivers (driverId),
    FOREIGN KEY (constructorId) REFERENCES constructors (constructorId)
);

CREATE TABLE races
(
    raceId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "year" NUMBER DEFAULT 0 NOT NULL,
    round NUMBER DEFAULT 0 NOT NULL,
    circuitId NUMBER DEFAULT 0 NOT NULL,
    "name" VARCHAR2(4000) DEFAULT '' NOT NULL,
    "date" DATE DEFAULT '0000-00-00' NOT NULL,
    "time" VARCHAR2(4000),
    url VARCHAR2(4000) UNIQUE,
    PRIMARY KEY (raceId),
    FOREIGN KEY ("year") REFERENCES seasons ("year"),
    FOREIGN KEY (circuitId) REFERENCES circuits (circuitId)
);

CREATE TABLE results
(
    resultId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    driverId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    "number" NUMBER,
    grid NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    positionText VARCHAR2(4000) DEFAULT '' NOT NULL,
    positionOrder NUMBER DEFAULT 0 NOT NULL,
    points NUMBER DEFAULT 0 NOT NULL,
    laps NUMBER DEFAULT 0 NOT NULL,
    "time" VARCHAR2(4000),
    milliseconds NUMBER,
    fastestLap NUMBER,
    "rank" NUMBER DEFAULT 0,
    fastestLapTime VARCHAR2(4000),
    fastestLapSpeed VARCHAR2(4000),
    statusId NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (resultId),
    FOREIGN KEY (raceId) REFERENCES races (raceId),
    FOREIGN KEY (driverId) REFERENCES drivers (driverId),
    FOREIGN KEY (constructorId) REFERENCES constructors (constructorId),
    FOREIGN KEY (statusId) REFERENCES "status" (statusId)
);

CREATE TABLE seasons
(
    "year" NUMBER DEFAULT 0 NOT NULL,
    url VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    PRIMARY KEY ("year")
);

CREATE TABLE "status"
(
    statusId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "status" VARCHAR2(4000) DEFAULT '' NOT NULL,
    PRIMARY KEY (statusId)
);
