-- Oracle DDL for formula_1.sqlite
-- Converted from SQLite schema

CREATE TABLE circuits
(
    circuitId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    circuitRef VARCHAR2(4000) DEFAULT '' NOT NULL,
    "name" VARCHAR2(4000) DEFAULT '' NOT NULL,
    "location" VARCHAR2(4000),
    country VARCHAR2(4000),
    lat NUMBER,
    lng NUMBER,
    alt NUMBER,
    url VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    PRIMARY KEY (circuitId)
);

CREATE TABLE constructorResults
(
    constructorResultsId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    points NUMBER,
    "status" VARCHAR2(4000),
    PRIMARY KEY (constructorResultsId)
);

CREATE TABLE constructorStandings
(
    constructorStandingsId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    points NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    positionText VARCHAR2(4000),
    wins NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (constructorStandingsId)
);

CREATE TABLE constructors
(
    constructorId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    constructorRef VARCHAR2(4000) DEFAULT '' NOT NULL,
    "name" VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    nationality VARCHAR2(4000),
    url VARCHAR2(4000) DEFAULT '' NOT NULL,
    PRIMARY KEY (constructorId)
);

CREATE TABLE driverStandings
(
    driverStandingsId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    driverId NUMBER DEFAULT 0 NOT NULL,
    points NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    positionText VARCHAR2(4000),
    wins NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (driverStandingsId)
);

CREATE TABLE drivers
(
    driverId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    driverRef VARCHAR2(4000) DEFAULT '' NOT NULL,
    "number" NUMBER,
    code VARCHAR2(4000),
    forename VARCHAR2(4000) DEFAULT '' NOT NULL,
    surname VARCHAR2(4000) DEFAULT '' NOT NULL,
    dob DATE,
    nationality VARCHAR2(4000),
    url VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    PRIMARY KEY (driverId)
);

CREATE TABLE lapTimes
(
    raceId NUMBER NOT NULL,
    driverId NUMBER NOT NULL,
    lap NUMBER NOT NULL,
    "position" NUMBER,
    "time" VARCHAR2(4000),
    milliseconds NUMBER,
    PRIMARY KEY (raceId, driverId, lap)
);

CREATE TABLE pitStops
(
    raceId NUMBER NOT NULL,
    driverId NUMBER NOT NULL,
    "stop" NUMBER NOT NULL,
    lap NUMBER NOT NULL,
    "time" VARCHAR2(4000) NOT NULL,
    duration VARCHAR2(4000),
    milliseconds NUMBER,
    PRIMARY KEY (raceId, driverId, "stop")
);

CREATE TABLE qualifying
(
    qualifyId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    driverId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    "number" NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    q1 VARCHAR2(4000),
    q2 VARCHAR2(4000),
    q3 VARCHAR2(4000),
    PRIMARY KEY (qualifyId)
);

CREATE TABLE races
(
    raceId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "year" NUMBER DEFAULT 0 NOT NULL,
    round NUMBER DEFAULT 0 NOT NULL,
    circuitId NUMBER DEFAULT 0 NOT NULL,
    "name" VARCHAR2(4000) DEFAULT '' NOT NULL,
    "date" DATE,
    "time" VARCHAR2(4000),
    url VARCHAR2(4000) UNIQUE,
    PRIMARY KEY (raceId)
);

CREATE TABLE results
(
    resultId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raceId NUMBER DEFAULT 0 NOT NULL,
    driverId NUMBER DEFAULT 0 NOT NULL,
    constructorId NUMBER DEFAULT 0 NOT NULL,
    "number" NUMBER,
    grid NUMBER DEFAULT 0 NOT NULL,
    "position" NUMBER,
    positionText VARCHAR2(4000) DEFAULT '' NOT NULL,
    positionOrder NUMBER DEFAULT 0 NOT NULL,
    points NUMBER DEFAULT 0 NOT NULL,
    laps NUMBER DEFAULT 0 NOT NULL,
    "time" VARCHAR2(4000),
    milliseconds NUMBER,
    fastestLap NUMBER,
    "rank" NUMBER DEFAULT 0,
    fastestLapTime VARCHAR2(4000),
    fastestLapSpeed VARCHAR2(4000),
    statusId NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (resultId)
);

CREATE TABLE seasons
(
    "year" NUMBER DEFAULT 0 NOT NULL,
    url VARCHAR2(4000) DEFAULT '' NOT NULL UNIQUE,
    PRIMARY KEY ("year")
);

CREATE TABLE "status"
(
    statusId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "status" VARCHAR2(4000) DEFAULT '' NOT NULL,
    PRIMARY KEY (statusId)
);

-- Deferred foreign key constraints
ALTER TABLE constructorResults ADD CONSTRAINT FK_CONSTRUCTORRESULTS_1 FOREIGN KEY (raceId) REFERENCES races (raceId);
ALTER TABLE constructorResults ADD CONSTRAINT FK_CONSTRUCTORRESULTS_2 FOREIGN KEY (constructorId) REFERENCES constructors (constructorId);
ALTER TABLE constructorStandings ADD CONSTRAINT FK_CONSTRUCTORSTANDINGS_1 FOREIGN KEY (raceId) REFERENCES races (raceId);
ALTER TABLE constructorStandings ADD CONSTRAINT FK_CONSTRUCTORSTANDINGS_2 FOREIGN KEY (constructorId) REFERENCES constructors (constructorId);
ALTER TABLE driverStandings ADD CONSTRAINT FK_DRIVERSTANDINGS_1 FOREIGN KEY (raceId) REFERENCES races (raceId);
ALTER TABLE driverStandings ADD CONSTRAINT FK_DRIVERSTANDINGS_2 FOREIGN KEY (driverId) REFERENCES drivers (driverId);
ALTER TABLE lapTimes ADD CONSTRAINT FK_LAPTIMES_1 FOREIGN KEY (raceId) REFERENCES races (raceId);
ALTER TABLE lapTimes ADD CONSTRAINT FK_LAPTIMES_2 FOREIGN KEY (driverId) REFERENCES drivers (driverId);
ALTER TABLE pitStops ADD CONSTRAINT FK_PITSTOPS_1 FOREIGN KEY (raceId) REFERENCES races (raceId);
ALTER TABLE pitStops ADD CONSTRAINT FK_PITSTOPS_2 FOREIGN KEY (driverId) REFERENCES drivers (driverId);
ALTER TABLE qualifying ADD CONSTRAINT FK_QUALIFYING_1 FOREIGN KEY (raceId) REFERENCES races (raceId);
ALTER TABLE qualifying ADD CONSTRAINT FK_QUALIFYING_2 FOREIGN KEY (driverId) REFERENCES drivers (driverId);
ALTER TABLE qualifying ADD CONSTRAINT FK_QUALIFYING_3 FOREIGN KEY (constructorId) REFERENCES constructors (constructorId);
ALTER TABLE races ADD CONSTRAINT FK_RACES_1 FOREIGN KEY ("year") REFERENCES seasons ("year");
ALTER TABLE races ADD CONSTRAINT FK_RACES_2 FOREIGN KEY (circuitId) REFERENCES circuits (circuitId);
ALTER TABLE results ADD CONSTRAINT FK_RESULTS_1 FOREIGN KEY (raceId) REFERENCES races (raceId);
ALTER TABLE results ADD CONSTRAINT FK_RESULTS_2 FOREIGN KEY (driverId) REFERENCES drivers (driverId);
ALTER TABLE results ADD CONSTRAINT FK_RESULTS_3 FOREIGN KEY (constructorId) REFERENCES constructors (constructorId);
ALTER TABLE results ADD CONSTRAINT FK_RESULTS_4 FOREIGN KEY (statusId) REFERENCES "status" (statusId);
