-- Oracle DDL for debit_card_specializing.sqlite
-- Converted from SQLite schema

CREATE TABLE customers
(
    CustomerID NUMBER NOT NULL,
    "Segment" VARCHAR2(4000),
    Currency VARCHAR2(4000),
    PRIMARY KEY (CustomerID)
);

CREATE TABLE gasstations
(
    GasStationID NUMBER NOT NULL,
    ChainID NUMBER,
    Country VARCHAR2(4000),
    "Segment" VARCHAR2(4000),
    PRIMARY KEY (GasStationID)
);

CREATE TABLE products
(
    ProductID NUMBER NOT NULL,
    Description VARCHAR2(4000),
    PRIMARY KEY (ProductID)
);

CREATE TABLE transactions_1k
(
    TransactionID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "Date" DATE,
    "Time" VARCHAR2(4000),
    CustomerID NUMBER,
    CardID NUMBER,
    GasStationID NUMBER,
    ProductID NUMBER,
    Amount NUMBER,
    Price NUMBER,
    PRIMARY KEY (TransactionID)
);

CREATE TABLE yearmonth
(
    CustomerID NUMBER NOT NULL,
    "Date" VARCHAR2(4000) NOT NULL,
    Consumption NUMBER,
    PRIMARY KEY ("Date", CustomerID)
);
