COMMENT ON COLUMN cards.artist IS 'The name of the artist that illustrated the card art.';
COMMENT ON COLUMN cards.asciiName IS 'The ASCII(opens new window) (Basic/128) code formatted card name with no special unicode characters.';
COMMENT ON COLUMN cards.availability IS 'A list of the card''s available printing types.';
ALTER TABLE cards MODIFY (availability ANNOTATIONS (ADD value_description '"arena", "dreamcast", "mtgo", "paper", "shandalar"'));
COMMENT ON COLUMN cards.borderColor IS 'The color of the card border.';
ALTER TABLE cards MODIFY (borderColor ANNOTATIONS (ADD value_description '"black", "borderless", "gold", "silver", "white"'));
COMMENT ON COLUMN cards.cardKingdomFoilId IS 'card Kingdom Foil Id';
ALTER TABLE cards MODIFY (cardKingdomFoilId ANNOTATIONS (ADD value_description 'commonsense evidence:cardKingdomFoilId, when paired with cardKingdomId that is not Null, is incredibly powerful.'));
COMMENT ON COLUMN cards.cardKingdomId IS 'card Kingdom Id';
ALTER TABLE cards MODIFY (cardKingdomId ANNOTATIONS (ADD value_description 'A list of all the colors in the color indicator'));
COMMENT ON COLUMN cards.colorIdentity IS 'A list of all the colors found in manaCost, colorIndicator, and text';
COMMENT ON COLUMN cards.colorIndicator IS 'A list of all the colors in the color indicator (The symbol prefixed to a card''s types).';
COMMENT ON COLUMN cards.colors IS 'A list of all the colors in manaCost and colorIndicator.';
ALTER TABLE cards MODIFY (colors ANNOTATIONS (ADD value_description 'Some cards may not have values, such as cards with "Devoid" in its text.'));
COMMENT ON COLUMN cards.convertedManaCost IS 'The converted mana cost of the card. Use the manaValue property.';
ALTER TABLE cards MODIFY (convertedManaCost ANNOTATIONS (ADD value_description 'if value is higher, it means that this card cost more converted mana'));
COMMENT ON COLUMN cards.duelDeck IS 'The indicator for which duel deck the card is in.';
COMMENT ON COLUMN cards.edhrecRank IS 'The card rank on EDHRec';
COMMENT ON COLUMN cards.faceConvertedManaCost IS 'The converted mana cost or mana value for the face for either half or part of the card.';
ALTER TABLE cards MODIFY (faceConvertedManaCost ANNOTATIONS (ADD value_description 'if value is higher, it means that this card cost more converted mana for the face'));
COMMENT ON COLUMN cards.faceName IS 'The name on the face of the card.';
COMMENT ON COLUMN cards.flavorName IS 'The promotional card name printed above the true card name on special cards that has no game function.';
ALTER TABLE cards MODIFY (flavorName ANNOTATIONS (ADD value_description 'The promotional card name printed above the true card name on special cards that has no game function.'));
COMMENT ON COLUMN cards.flavorText IS 'The italicized text found below the rules text that has no game function.';
ALTER TABLE cards MODIFY (flavorText ANNOTATIONS (ADD value_description 'The italicized text found below the rules text that has no game function.'));
COMMENT ON COLUMN cards.frameEffects IS 'The visual frame effects.';
ALTER TABLE cards MODIFY (frameEffects ANNOTATIONS (ADD value_description '"colorshifted", "companion", "compasslanddfc", "devoid", "draft", "etched", "extendedart", "fullart", "inverted", "legendary", "lesson", "miracle", "mooneldrazidfc", "nyxtouched", "originpwdfc", "showcase", "snow", "sunmoondfc", "textless", "tombstone", "waxingandwaningmoondfc"'));
COMMENT ON COLUMN cards.frameVersion IS 'The version of the card frame style.';
ALTER TABLE cards MODIFY (frameVersion ANNOTATIONS (ADD value_description '"1993", "1997", "2003", "2015", "future"'));
COMMENT ON COLUMN cards.hand IS 'The starting maximum hand size total modifier.';
ALTER TABLE cards MODIFY (hand ANNOTATIONS (ADD value_description 'A + or - character precedes an integer. commonsense evidence:positive maximum hand size: +1, +2, ....negative maximum hand size: -1, ....neural maximum hand size: 0....'));
COMMENT ON COLUMN cards.hasAlternativeDeckLimit IS 'If the card allows a value other than 4 copies in a deck.';
ALTER TABLE cards MODIFY (hasAlternativeDeckLimit ANNOTATIONS (ADD value_description '0: disallow 1: allow'));
COMMENT ON COLUMN cards.hasContentWarning IS 'If the card marked by Wizards of the Coast (opens new window) for having sensitive content. See this official article (opens new window) for more information.';
ALTER TABLE cards MODIFY (hasContentWarning ANNOTATIONS (ADD value_description '0: doesn''t have 1: has sensitve content or Wizards of the Coastcommonsense evidence:Cards with this property may have missing or degraded properties and values.'));
COMMENT ON COLUMN cards.hasFoil IS 'If the card can be found in foil';
ALTER TABLE cards MODIFY (hasFoil ANNOTATIONS (ADD value_description '0: cannot be found 1: can be found'));
COMMENT ON COLUMN cards.hasNonFoil IS 'If the card can be found in non-foil';
ALTER TABLE cards MODIFY (hasNonFoil ANNOTATIONS (ADD value_description '0: cannot be found 1: can be found'));
COMMENT ON COLUMN cards.isAlternative IS 'If the card is an alternate variation to an original printing';
ALTER TABLE cards MODIFY (isAlternative ANNOTATIONS (ADD value_description '0: is not 1: is'));
COMMENT ON COLUMN cards.isFullArt IS 'If the card has full artwork.';
ALTER TABLE cards MODIFY (isFullArt ANNOTATIONS (ADD value_description '0: doesn''t have, 1: has full artwork'));
COMMENT ON COLUMN cards.isOnlineOnly IS 'If the card is only available in online game variations.';
ALTER TABLE cards MODIFY (isOnlineOnly ANNOTATIONS (ADD value_description '0: is not 1: is'));
COMMENT ON COLUMN cards.isOversized IS 'If the card is oversized.';
ALTER TABLE cards MODIFY (isOversized ANNOTATIONS (ADD value_description '0: is not 1: is'));
COMMENT ON COLUMN cards.isPromo IS 'If the card is a promotional printing.';
ALTER TABLE cards MODIFY (isPromo ANNOTATIONS (ADD value_description '0: is not 1: is'));
COMMENT ON COLUMN cards.isReprint IS 'If the card has been reprinted.';
ALTER TABLE cards MODIFY (isReprint ANNOTATIONS (ADD value_description '0: has not 1: has not been'));
COMMENT ON COLUMN cards.isReserved IS 'If the card is on the Magic: The Gathering Reserved List (opens new window)';
ALTER TABLE cards MODIFY (isReserved ANNOTATIONS (ADD value_description 'If the card is on the Magic, it will appear in The Gathering Reserved List'));
COMMENT ON COLUMN cards.isStarter IS 'If the card is found in a starter deck such as Planeswalker/Brawl decks.';
ALTER TABLE cards MODIFY (isStarter ANNOTATIONS (ADD value_description '0: is not 1: is'));
COMMENT ON COLUMN cards.isStorySpotlight IS 'If the card is a Story Spotlight card.';
ALTER TABLE cards MODIFY (isStorySpotlight ANNOTATIONS (ADD value_description '0: is not 1: is'));
COMMENT ON COLUMN cards.isTextless IS 'If the card does not have a text box.';
ALTER TABLE cards MODIFY (isTextless ANNOTATIONS (ADD value_description 'commonsense evidence:0: has a text box;1: doesn''t have a text box;'));
COMMENT ON COLUMN cards.isTimeshifted IS 'If the card is time shifted';
ALTER TABLE cards MODIFY (isTimeshifted ANNOTATIONS (ADD value_description 'commonsense evidence:If the card is "timeshifted", a feature of certain sets where a card will have a different frameVersion.'));
COMMENT ON COLUMN cards.keywords IS 'A list of keywords found on the card.';
COMMENT ON COLUMN cards.layout IS 'The type of card layout. For a token card, this will be "token"';
COMMENT ON COLUMN cards.leadershipSkills IS 'A list of formats the card is legal to be a commander in';
COMMENT ON COLUMN cards.life IS 'The starting life total modifier. A plus or minus character precedes an integer.';
COMMENT ON COLUMN cards.loyalty IS 'The starting loyalty value of the card.';
ALTER TABLE cards MODIFY (loyalty ANNOTATIONS (ADD value_description 'Used only on cards with "Planeswalker" in its types. empty means unkown'));
COMMENT ON COLUMN cards.manaCost IS 'The mana cost of the card wrapped in brackets for each value.';
ALTER TABLE cards MODIFY (manaCost ANNOTATIONS (ADD value_description 'commonsense evidence:manaCost is unconverted mana cost'));
ALTER TABLE cards MODIFY (mcmId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (mcmMetaId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (mtgArenaId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (mtgjsonV4Id ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (mtgoFoilId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (mtgoId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (multiverseId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
COMMENT ON COLUMN cards."name" IS 'The name of the card.';
ALTER TABLE cards MODIFY ("name" ANNOTATIONS (ADD value_description 'Cards with multiple faces, like "Split" and "Meld" cards are given a delimiter.'));
COMMENT ON COLUMN cards."number" IS 'The number of the card';
COMMENT ON COLUMN cards.originalReleaseDate IS 'original Release Date';
ALTER TABLE cards MODIFY (originalReleaseDate ANNOTATIONS (ADD value_description 'The original release date in ISO 8601(opens new window) format for a promotional card printed outside of a cycle window, such as Secret Lair Drop promotions.'));
COMMENT ON COLUMN cards.originalText IS 'original Text';
ALTER TABLE cards MODIFY (originalText ANNOTATIONS (ADD value_description 'The text on the card as originally printed.'));
COMMENT ON COLUMN cards.originalType IS 'original Type';
ALTER TABLE cards MODIFY (originalType ANNOTATIONS (ADD value_description 'The type of the card as originally printed. Includes any supertypes and subtypes.'));
COMMENT ON COLUMN cards.otherFaceIds IS 'other Face Ids';
ALTER TABLE cards MODIFY (otherFaceIds ANNOTATIONS (ADD value_description 'A list of card UUID''s to this card''s counterparts, such as transformed or melded faces.'));
COMMENT ON COLUMN cards.power IS 'The power of the card.';
ALTER TABLE cards MODIFY (power ANNOTATIONS (ADD value_description 'commonsense evidence:∞ means infinite powernull or * refers to unknown power'));
COMMENT ON COLUMN cards.printings IS 'A list of set printing codes the card was printed in, formatted in uppercase.';
COMMENT ON COLUMN cards.promoTypes IS 'A list of promotional types for a card.';
ALTER TABLE cards MODIFY (promoTypes ANNOTATIONS (ADD value_description '"arenaleague", "boosterfun", "boxtopper", "brawldeck", "bundle", "buyabox", "convention", "datestamped", "draculaseries", "draftweekend", "duels", "event", "fnm", "gameday", "gateway", "giftbox", "gilded", "godzillaseries", "instore", "intropack", "jpwalker", "judgegift", "league", "mediainsert", "neonink", "openhouse", "planeswalkerstamped", "playerrewards", "playpromo", "premiereshop", "prerelease", "promopack", "release", "setpromo", "stamped", "textured", "themepack", "thick", "tourney", "wizardsplaynetwork"'));
COMMENT ON COLUMN cards.purchaseUrls IS 'Links that navigate to websites where the card can be purchased.';
COMMENT ON COLUMN cards.rarity IS 'The card printing rarity.';
ALTER TABLE cards MODIFY (scryfallId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (scryfallIllustrationId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
ALTER TABLE cards MODIFY (scryfallOracleId ANNOTATIONS (ADD value_description 'NOT USEFUL'));
COMMENT ON COLUMN cards.setCode IS 'The set printing code that the card is from.';
COMMENT ON COLUMN cards.side IS 'The identifier of the card side.';
ALTER TABLE cards MODIFY (side ANNOTATIONS (ADD value_description 'Used on cards with multiple faces on the same card.commonsense evidence:if this value is empty, then it means this card doesn''t have multiple faces on the same card.'));
COMMENT ON COLUMN cards.subtypes IS 'A list of card subtypes found after em-dash.';
COMMENT ON COLUMN cards.supertypes IS 'A list of card supertypes found before em-dash.';
ALTER TABLE cards MODIFY (supertypes ANNOTATIONS (ADD value_description 'commonsense evidence:list of all types should be the union of subtypes and supertypes'));
COMMENT ON COLUMN cards."text" IS 'The rules text of the card.';
COMMENT ON COLUMN cards.toughness IS 'The toughness of the card.';
COMMENT ON COLUMN cards."type" IS 'The type of the card as visible, including any supertypes and subtypes.';
ALTER TABLE cards MODIFY ("type" ANNOTATIONS (ADD value_description '"Artifact", "Card", "Conspiracy", "Creature", "Dragon", "Dungeon", "Eaturecray", "Elemental", "Elite", "Emblem", "Enchantment", "Ever", "Goblin", "Hero", "Instant", "Jaguar", "Knights", "Land", "Phenomenon", "Plane", "Planeswalker", "Scariest", "Scheme", "See", "Sorcery", "Sticker", "Summon", "Token", "Tribal", "Vanguard", "Wolf", "You’ll", "instant"'));
COMMENT ON COLUMN cards."types" IS 'A list of all card types of the card, including Un‑sets and gameplay variants.';
COMMENT ON COLUMN cards.uuid IS 'The universal unique identifier (v5) generated by MTGJSON. Each entry is unique.';
ALTER TABLE cards MODIFY (uuid ANNOTATIONS (ADD value_description 'NOT USEFUL'));
COMMENT ON COLUMN cards.watermark IS 'The name of the watermark on the card.';

COMMENT ON COLUMN foreign_data.id IS 'unique id number identifying this row of data';
COMMENT ON COLUMN foreign_data.flavorText IS 'The foreign flavor text of the card.';
COMMENT ON COLUMN foreign_data."language" IS 'The foreign language of card.';
COMMENT ON COLUMN foreign_data.multiverseid IS 'The foreign multiverse identifier of the card.';
COMMENT ON COLUMN foreign_data."name" IS 'The foreign name of the card.';
COMMENT ON COLUMN foreign_data."text" IS 'The foreign text ruling of the card.';
COMMENT ON COLUMN foreign_data."type" IS 'The foreign type of the card. Includes any supertypes and subtypes.';

COMMENT ON COLUMN legalities.id IS 'unique id identifying this legality';
COMMENT ON COLUMN legalities."format" IS 'format of play';
ALTER TABLE legalities MODIFY ("format" ANNOTATIONS (ADD value_description 'each value refers to different rules to play'));
ALTER TABLE legalities MODIFY ("status" ANNOTATIONS (ADD value_description '• legal• banned• restricted'));

COMMENT ON COLUMN rulings.id IS 'unique id identifying this ruling';
COMMENT ON COLUMN rulings."date" IS 'date';
COMMENT ON COLUMN rulings."text" IS 'description about this ruling';

COMMENT ON COLUMN set_translations.id IS 'unique id identifying this set';
COMMENT ON COLUMN set_translations."language" IS 'language of this card set';
COMMENT ON COLUMN set_translations.setCode IS 'the set code for this set';
COMMENT ON COLUMN set_translations.translation IS 'translation of this card set';

COMMENT ON COLUMN sets.id IS 'unique id identifying this set';
COMMENT ON COLUMN sets.baseSetSize IS 'The number of cards in the set.';
COMMENT ON COLUMN sets."block" IS 'The block name the set was in.';
COMMENT ON COLUMN sets.booster IS 'A breakdown of possibilities and weights of cards in a booster pack.';
COMMENT ON COLUMN sets.code IS 'The set code for the set.';
COMMENT ON COLUMN sets.isFoilOnly IS 'If the set is only available in foil.';
COMMENT ON COLUMN sets.isForeignOnly IS 'If the set is available only outside the United States of America.';
COMMENT ON COLUMN sets.isNonFoilOnly IS 'If the set is only available in non-foil.';
COMMENT ON COLUMN sets.isOnlineOnly IS 'If the set is only available in online game variations.';
COMMENT ON COLUMN sets.isPartialPreview IS 'If the set is still in preview (spoiled). Preview sets do not have complete data.';
COMMENT ON COLUMN sets.keyruneCode IS 'The matching Keyrune code for set image icons.';
COMMENT ON COLUMN sets.mcmId IS 'The Magic Card Marketset identifier.';
COMMENT ON COLUMN sets.mcmIdExtras IS 'The split Magic Card Market set identifier if a set is printed in two sets. This identifier represents the second set''s identifier.';
COMMENT ON COLUMN sets.mtgoCode IS 'The set code for the set as it appears on Magic: The Gathering Online';
ALTER TABLE sets MODIFY (mtgoCode ANNOTATIONS (ADD value_description 'commonsense evidence:if the value is null or empty, then it doesn''t appear on Magic: The Gathering Online'));
COMMENT ON COLUMN sets."name" IS 'The name of the set.';
COMMENT ON COLUMN sets.parentCode IS 'The parent set code for set variations like promotions, guild kits, etc.';
COMMENT ON COLUMN sets.releaseDate IS 'The release date in ISO 8601 format for the set.';
COMMENT ON COLUMN sets.tcgplayerGroupId IS 'The group identifier of the set on TCGplayer';
COMMENT ON COLUMN sets.totalSetSize IS 'The total number of cards in the set, including promotional and related supplemental products but excluding Alchemy modifications - however those cards are included in the set itself.';
COMMENT ON COLUMN sets."type" IS 'The expansion type of the set.';
ALTER TABLE sets MODIFY ("type" ANNOTATIONS (ADD value_description '"alchemy", "archenemy", "arsenal", "box", "commander", "core", "draft_innovation", "duel_deck", "expansion", "from_the_vault", "funny", "masterpiece", "masters", "memorabilia", "planechase", "premium_deck", "promo", "spellbook", "starter", "token", "treasure_chest", "vanguard"'));
