-- Oracle DDL for card_games.sqlite
-- Converted from SQLite schema

CREATE TABLE cards
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    artist VARCHAR2(4000),
    asciiName VARCHAR2(4000),
    availability VARCHAR2(4000),
    borderColor VARCHAR2(4000),
    cardKingdomFoilId VARCHAR2(4000),
    cardKingdomId VARCHAR2(4000),
    colorIdentity VARCHAR2(4000),
    colorIndicator VARCHAR2(4000),
    colors VARCHAR2(4000),
    convertedManaCost NUMBER,
    duelDeck VARCHAR2(4000),
    edhrecRank NUMBER,
    faceConvertedManaCost NUMBER,
    faceName VARCHAR2(4000),
    flavorName VARCHAR2(4000),
    flavorText VARCHAR2(4000),
    frameEffects VARCHAR2(4000),
    frameVersion VARCHAR2(4000),
    hand VARCHAR2(4000),
    hasAlternativeDeckLimit NUMBER DEFAULT 0 NOT NULL,
    hasContentWarning NUMBER DEFAULT 0 NOT NULL,
    hasFoil NUMBER DEFAULT 0 NOT NULL,
    hasNonFoil NUMBER DEFAULT 0 NOT NULL,
    isAlternative NUMBER DEFAULT 0 NOT NULL,
    isFullArt NUMBER DEFAULT 0 NOT NULL,
    isOnlineOnly NUMBER DEFAULT 0 NOT NULL,
    isOversized NUMBER DEFAULT 0 NOT NULL,
    isPromo NUMBER DEFAULT 0 NOT NULL,
    isReprint NUMBER DEFAULT 0 NOT NULL,
    isReserved NUMBER DEFAULT 0 NOT NULL,
    isStarter NUMBER DEFAULT 0 NOT NULL,
    isStorySpotlight NUMBER DEFAULT 0 NOT NULL,
    isTextless NUMBER DEFAULT 0 NOT NULL,
    isTimeshifted NUMBER DEFAULT 0 NOT NULL,
    keywords VARCHAR2(4000),
    layout VARCHAR2(4000),
    leadershipSkills VARCHAR2(4000),
    life VARCHAR2(4000),
    loyalty VARCHAR2(4000),
    manaCost VARCHAR2(4000),
    mcmId VARCHAR2(4000),
    mcmMetaId VARCHAR2(4000),
    mtgArenaId VARCHAR2(4000),
    mtgjsonV4Id VARCHAR2(4000),
    mtgoFoilId VARCHAR2(4000),
    mtgoId VARCHAR2(4000),
    multiverseId VARCHAR2(4000),
    "name" VARCHAR2(4000),
    "number" VARCHAR2(4000),
    originalReleaseDate VARCHAR2(4000),
    originalText VARCHAR2(4000),
    originalType VARCHAR2(4000),
    otherFaceIds VARCHAR2(4000),
    power VARCHAR2(4000),
    printings VARCHAR2(4000),
    promoTypes VARCHAR2(4000),
    purchaseUrls VARCHAR2(4000),
    rarity VARCHAR2(4000),
    scryfallId VARCHAR2(4000),
    scryfallIllustrationId VARCHAR2(4000),
    scryfallOracleId VARCHAR2(4000),
    setCode VARCHAR2(4000),
    side VARCHAR2(4000),
    subtypes VARCHAR2(4000),
    supertypes VARCHAR2(4000),
    tcgplayerProductId VARCHAR2(4000),
    "text" VARCHAR2(4000),
    toughness VARCHAR2(4000),
    "type" VARCHAR2(4000),
    "types" VARCHAR2(4000),
    uuid VARCHAR2(4000) NOT NULL UNIQUE,
    variations VARCHAR2(4000),
    watermark VARCHAR2(4000),
    PRIMARY KEY (id)
);

CREATE TABLE foreign_data
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flavorText VARCHAR2(4000),
    "language" VARCHAR2(4000),
    multiverseid NUMBER,
    "name" VARCHAR2(4000),
    "text" VARCHAR2(4000),
    "type" VARCHAR2(4000),
    uuid VARCHAR2(4000),
    PRIMARY KEY (id)
);

CREATE TABLE legalities
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "format" VARCHAR2(4000),
    "status" VARCHAR2(4000),
    uuid VARCHAR2(4000),
    PRIMARY KEY (id)
);

CREATE TABLE rulings
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "date" DATE,
    "text" VARCHAR2(4000),
    uuid VARCHAR2(4000),
    PRIMARY KEY (id)
);

CREATE TABLE set_translations
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "language" VARCHAR2(4000),
    setCode VARCHAR2(4000),
    translation VARCHAR2(4000),
    PRIMARY KEY (id)
);

CREATE TABLE "sets"
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    baseSetSize NUMBER,
    "block" VARCHAR2(4000),
    booster VARCHAR2(4000),
    code VARCHAR2(4000) NOT NULL UNIQUE,
    isFoilOnly NUMBER DEFAULT 0 NOT NULL,
    isForeignOnly NUMBER DEFAULT 0 NOT NULL,
    isNonFoilOnly NUMBER DEFAULT 0 NOT NULL,
    isOnlineOnly NUMBER DEFAULT 0 NOT NULL,
    isPartialPreview NUMBER DEFAULT 0 NOT NULL,
    keyruneCode VARCHAR2(4000),
    mcmId NUMBER,
    mcmIdExtras NUMBER,
    mcmName VARCHAR2(4000),
    mtgoCode VARCHAR2(4000),
    "name" VARCHAR2(4000),
    parentCode VARCHAR2(4000),
    releaseDate DATE,
    tcgplayerGroupId NUMBER,
    totalSetSize NUMBER,
    "type" VARCHAR2(4000),
    PRIMARY KEY (id)
);

-- Deferred foreign key constraints
ALTER TABLE foreign_data ADD CONSTRAINT FK_FOREIGN_DATA_1 FOREIGN KEY (uuid) REFERENCES cards (uuid);
ALTER TABLE legalities ADD CONSTRAINT FK_LEGALITIES_1 FOREIGN KEY (uuid) REFERENCES cards (uuid);
ALTER TABLE rulings ADD CONSTRAINT FK_RULINGS_1 FOREIGN KEY (uuid) REFERENCES cards (uuid);
ALTER TABLE set_translations ADD CONSTRAINT FK_SET_TRANSLATIONS_1 FOREIGN KEY (setCode) REFERENCES "sets" (code);
