COMMENT ON COLUMN frpm.CDSCode IS 'CDSCode';
COMMENT ON COLUMN frpm."Academic Year" IS 'Academic Year';
COMMENT ON COLUMN frpm."County Code" IS 'County Code';
COMMENT ON COLUMN frpm."District Code" IS 'District Code';
COMMENT ON COLUMN frpm."School Code" IS 'School Code';
COMMENT ON COLUMN frpm."County Name" IS 'County Code';
COMMENT ON COLUMN frpm."District Name" IS 'District Name';
COMMENT ON COLUMN frpm."School Name" IS 'School Name';
COMMENT ON COLUMN frpm."District Type" IS 'District Type';
COMMENT ON COLUMN frpm."School Type" IS 'School Type';
COMMENT ON COLUMN frpm."Educational Option Type" IS 'Educational Option Type';
COMMENT ON COLUMN frpm."NSLP Provision Status" IS 'NSLP Provision Status';
COMMENT ON COLUMN frpm."Charter School (Y/N)" IS 'Charter School (Y/N)';
ALTER TABLE frpm MODIFY ("Charter School (Y/N)" ANNOTATIONS (ADD value_description '0: N;1: Y'));
COMMENT ON COLUMN frpm."Charter School Number" IS 'Charter School Number';
COMMENT ON COLUMN frpm."Charter Funding Type" IS 'Charter Funding Type';
ALTER TABLE frpm MODIFY (IRC ANNOTATIONS (ADD value_description 'Not useful'));
COMMENT ON COLUMN frpm."Low Grade" IS 'Low Grade';
COMMENT ON COLUMN frpm."High Grade" IS 'High Grade';
COMMENT ON COLUMN frpm."Enrollment (K-12)" IS 'Enrollment (K-12)';
ALTER TABLE frpm MODIFY ("Enrollment (K-12)" ANNOTATIONS (ADD value_description 'commonsense evidence:K-12: 1st grade - 12nd grade'));
COMMENT ON COLUMN frpm."Free Meal Count (K-12)" IS 'Free Meal Count (K-12)';
ALTER TABLE frpm MODIFY ("Free Meal Count (K-12)" ANNOTATIONS (ADD value_description 'commonsense evidence:eligible free rate = Free Meal Count / Enrollment'));
COMMENT ON COLUMN frpm."FRPM Count (K-12)" IS 'Free or Reduced Price Meal Count (K-12)';
ALTER TABLE frpm MODIFY ("FRPM Count (K-12)" ANNOTATIONS (ADD value_description 'commonsense evidence:eligible FRPM rate = FRPM / Enrollment'));
COMMENT ON COLUMN frpm."Enrollment (Ages 5-17)" IS 'Enrollment (Ages 5-17)';
COMMENT ON COLUMN frpm."Free Meal Count (Ages 5-17)" IS 'Free Meal Count (Ages 5-17)';
ALTER TABLE frpm MODIFY ("Free Meal Count (Ages 5-17)" ANNOTATIONS (ADD value_description 'commonsense evidence:eligible free rate = Free Meal Count / Enrollment'));
COMMENT ON COLUMN frpm."2013-14 CALPADS Fall 1 Certification Status" IS '2013-14 CALPADS Fall 1 Certification Status';

COMMENT ON COLUMN satscores.cds IS 'California Department Schools';
COMMENT ON COLUMN satscores.rtype IS 'rtype';
ALTER TABLE satscores MODIFY (rtype ANNOTATIONS (ADD value_description 'unuseful'));
COMMENT ON COLUMN satscores.sname IS 'school name';
COMMENT ON COLUMN satscores.dname IS 'district segment';
COMMENT ON COLUMN satscores.cname IS 'county name';
COMMENT ON COLUMN satscores.enroll12 IS 'enrollment (1st-12nd grade)';
COMMENT ON COLUMN satscores.NumTstTakr IS 'Number of Test Takers in this school';
ALTER TABLE satscores MODIFY (NumTstTakr ANNOTATIONS (ADD value_description 'number of test takers in each school'));
COMMENT ON COLUMN satscores.AvgScrRead IS 'average scores in Reading';
ALTER TABLE satscores MODIFY (AvgScrRead ANNOTATIONS (ADD value_description 'average scores in Reading'));
COMMENT ON COLUMN satscores.AvgScrMath IS 'average scores in Math';
ALTER TABLE satscores MODIFY (AvgScrMath ANNOTATIONS (ADD value_description 'average scores in Math'));
COMMENT ON COLUMN satscores.AvgScrWrite IS 'average scores in writing';
ALTER TABLE satscores MODIFY (AvgScrWrite ANNOTATIONS (ADD value_description 'average scores in writing'));
COMMENT ON COLUMN satscores.NumGE1500 IS 'Number of Test Takers Whose Total SAT Scores Are Greater or Equal to 1500';
ALTER TABLE satscores MODIFY (NumGE1500 ANNOTATIONS (ADD value_description 'Number of Test Takers Whose Total SAT Scores Are Greater or Equal to 1500commonsense evidence:Excellence Rate = NumGE1500 / NumTstTakr'));

COMMENT ON COLUMN schools.CDSCode IS 'CDSCode';
COMMENT ON COLUMN schools.NCESDist IS 'This field represents the 7-digit National Center for Educational Statistics (NCES) school district identification number. The first 2 digits identify the state and the last 5 digits identify the school district. Combined, they make a unique 7-digit ID for each school district.';
COMMENT ON COLUMN schools.NCESSchool IS 'This field represents the 5-digit NCES school identification number. The NCESSchool combined with the NCESDist form a unique 12-digit ID for each school.';
COMMENT ON COLUMN schools.StatusType IS 'This field identifies the status of the district.';
ALTER TABLE schools MODIFY (StatusType ANNOTATIONS (ADD value_description 'Definitions of the valid status types are listed below:· Active: The district is in operation and providing instructional services.· Closed: The district is not in operation and no longer providing instructional services.· Merged: The district has combined with another district or districts.· Pending: The district has not opened for operation and instructional services yet, but plans to open within the next 9–12 months.'));
COMMENT ON COLUMN schools.County IS 'County name';
COMMENT ON COLUMN schools.District IS 'District';
COMMENT ON COLUMN schools.School IS 'School';
COMMENT ON COLUMN schools.Street IS 'Street';
COMMENT ON COLUMN schools.StreetAbr IS 'The abbreviated street address of the school, district, or administrative authority’s physical location.';
ALTER TABLE schools MODIFY (StreetAbr ANNOTATIONS (ADD value_description 'The abbreviated street address of the school, district, or administrative authority’s physical location. Note: Some records (primarily records of closed or retired schools) may not have data in this field.'));
COMMENT ON COLUMN schools.City IS 'City';
COMMENT ON COLUMN schools.Zip IS 'Zip';
COMMENT ON COLUMN schools.State IS 'State';
COMMENT ON COLUMN schools.MailStreet IS 'MailStreet';
ALTER TABLE schools MODIFY (MailStreet ANNOTATIONS (ADD value_description 'The unabbreviated mailing address of the school, district, or administrative authority. Note: 1) Some entities (primarily closed or retired schools) may not have data in this field; 2) Many active entities have not provided a mailing street address. For your convenience we have filled the unpopulated MailStreet cells with Street data.'));
ALTER TABLE schools MODIFY (MailStrAbr ANNOTATIONS (ADD value_description 'the abbreviated mailing street address of the school, district, or administrative authority.Note: Many active entities have not provided a mailing street address. For your convenience we have filled the unpopulated MailStrAbr cells with StreetAbr data.'));
ALTER TABLE schools MODIFY (MailCity ANNOTATIONS (ADD value_description 'The city associated with the mailing address of the school, district, or administrative authority. Note: Many entities have not provided a mailing address city. For your convenience we have filled the unpopulated MailCity cells with City data.'));
ALTER TABLE schools MODIFY (MailZip ANNOTATIONS (ADD value_description 'The zip code associated with the mailing address of the school, district, or administrative authority. Note: Many entities have not provided a mailing address zip code. For your convenience we have filled the unpopulated MailZip cells with Zip data.'));
ALTER TABLE schools MODIFY (MailState ANNOTATIONS (ADD value_description 'The state within the mailing address. For your convenience we have filled the unpopulated MailState cells with State data.'));
COMMENT ON COLUMN schools.Phone IS 'Phone';
COMMENT ON COLUMN schools.Ext IS 'The phone number extension of the school, district, or administrative authority.';
ALTER TABLE schools MODIFY (Ext ANNOTATIONS (ADD value_description 'The phone number extension of the school, district, or administrative authority.'));
COMMENT ON COLUMN schools.Website IS 'The website address of the school, district, or administrative authority.';
ALTER TABLE schools MODIFY (Website ANNOTATIONS (ADD value_description 'The website address of the school, district, or administrative authority.'));
COMMENT ON COLUMN schools.OpenDate IS 'The date the school opened.';
COMMENT ON COLUMN schools.ClosedDate IS 'The date the school closed.';
COMMENT ON COLUMN schools.Charter IS 'This field identifies a charter school.';
ALTER TABLE schools MODIFY (Charter ANNOTATIONS (ADD value_description 'The field is coded as follows:· 1 = The school is a charter· 0 = The school is not a charter'));
COMMENT ON COLUMN schools.CharterNum IS 'The charter school number,';
ALTER TABLE schools MODIFY (CharterNum ANNOTATIONS (ADD value_description '4-digit number assigned to a charter school.'));
COMMENT ON COLUMN schools.FundingType IS 'Indicates the charter school funding type';
ALTER TABLE schools MODIFY (FundingType ANNOTATIONS (ADD value_description 'Values are as follows:· Not in CS (California School) funding model· Locally funded· Directly funded'));
COMMENT ON COLUMN schools.DOC IS 'District Ownership Code';
ALTER TABLE schools MODIFY (DOC ANNOTATIONS (ADD value_description 'The District Ownership Code (DOC) is the numeric code used to identify the category of the Administrative Authority.• 00 - County Office of Education• 02 – State Board of Education• 03 – Statewide Benefit Charter• 31 – State Special Schools• 34 – Non-school Location*• 52 – Elementary School District• 54 – Unified School District• 56 – High School District• 98 – Regional Occupational Center/Program (ROC/P)commonsense evidence:*Only the California Education Authority has been included in the non-school location category.'));
COMMENT ON COLUMN schools.DOCType IS 'The District Ownership Code Type is the text description of the DOC category.';
ALTER TABLE schools MODIFY (DOCType ANNOTATIONS (ADD value_description '(See text values in DOC field description above)'));
COMMENT ON COLUMN schools.SOC IS 'The School Ownership Code is a numeric code used to identify the type of school.';
ALTER TABLE schools MODIFY (SOC ANNOTATIONS (ADD value_description '• 08 - Preschool • 09 – Special Education Schools (Public)• 11 – Youth Authority Facilities (CEA)• 13 – Opportunity Schools• 14 – Juvenile Court Schools• 15 – Other County or District Programs• 31 – State Special Schools• 60 – Elementary School (Public)• 61 – Elementary School in 1 School District (Public)• 62 – Intermediate/Middle Schools (Public)• 63 – Alternative Schools of Choice• 64 – Junior High Schools (Public)• 65 – K-12 Schools (Public)• 66 – High Schools (Public)• 67 – High Schools in 1 School District (Public)• 68 – Continuation High Schools• 69 – District Community Day Schools• 70 – Adult Education Centers• 98 – Regional Occupational Center/Program (ROC/P)'));
COMMENT ON COLUMN schools.SOCType IS 'The School Ownership Code Type is the text description of the type of school.';
ALTER TABLE schools MODIFY (SOCType ANNOTATIONS (ADD value_description 'The School Ownership Code Type is the text description of the type of school.'));
COMMENT ON COLUMN schools.EdOpsCode IS 'The Education Option Code is a short text description of the type of education offered.';
ALTER TABLE schools MODIFY (EdOpsCode ANNOTATIONS (ADD value_description '• ALTSOC – Alternative School of Choice• COMM – County Community School• COMMDAY – Community Day School• CON – Continuation School• JUV – Juvenile Court School• OPP – Opportunity School• YTH – Youth Authority School• SSS – State Special School• SPEC – Special Education School• TRAD – Traditional• ROP – Regional Occupational Program• HOMHOS – Home and Hospital• SPECON – District Consortia Special Education School'));
COMMENT ON COLUMN schools.EdOpsName IS 'Educational Option Name';
ALTER TABLE schools MODIFY (EdOpsName ANNOTATIONS (ADD value_description 'The Educational Option Name is the long text description of the type of education being offered.'));
COMMENT ON COLUMN schools.EILCode IS 'The Educational Instruction Level Code is a short text description of the institution''s type relative to the grade range served.';
ALTER TABLE schools MODIFY (EILCode ANNOTATIONS (ADD value_description '• A – Adult• ELEM – Elementary• ELEMHIGH – Elementary-High Combination• HS – High School• INTMIDJR – Intermediate/Middle/Junior High• PS – Preschool• UG – Ungraded'));
COMMENT ON COLUMN schools.EILName IS 'The Educational Instruction Level Name is the long text description of the institution’s type relative to the grade range served.';
ALTER TABLE schools MODIFY (EILName ANNOTATIONS (ADD value_description 'The Educational Instruction Level Name is the long text description of the institution’s type relative to the grade range served.'));
COMMENT ON COLUMN schools.GSoffered IS 'The grade span offered is the lowest grade and the highest grade offered or supported by the school, district, or administrative authority. This field might differ from the grade span served as reported in the most recent certified California Longitudinal Pupil Achievement (CALPADS) Fall 1 data collection.';
ALTER TABLE schools MODIFY (GSoffered ANNOTATIONS (ADD value_description 'For example XYZ School might display the following data:GSoffered = P–AdultGSserved = K–12'));
COMMENT ON COLUMN schools.GSserved IS 'It is the lowest grade and the highest grade of student enrollment as reported in the most recent certified CALPADS Fall 1 data collection. Only K–12 enrollment is reported through CALPADS. This field may differ from the grade span offered.';
ALTER TABLE schools MODIFY (GSserved ANNOTATIONS (ADD value_description 'commonsense evidence:1. Only K–12 enrollment is reported through CALPADS2. Note: Special programs at independent study, alternative education, and special education schools will often exceed the typical grade span for schools of that type'));
COMMENT ON COLUMN schools."Virtual" IS 'This field identifies the type of virtual instruction offered by the school. Virtual instruction is instruction in which students and teachers are separated by time and/or location, and interaction occurs via computers and/or telecommunications technologies.';
ALTER TABLE schools MODIFY ("Virtual" ANNOTATIONS (ADD value_description 'The field is coded as follows:· F = Exclusively Virtual – The school has no physical building where students meet with each other or with teachers, all instruction is virtual.· V = Primarily Virtual – The school focuses on a systematic program of virtual instruction but includes some physical meetings among students or with teachers.· C = Primarily Classroom – The school offers virtual courses but virtual instruction is not the primary means of instruction.· N = Not Virtual – The school does not offer any virtual instruction.· P = Partial Virtual – The school offers some, but not all, instruction through virtual instruction. Note: This value was retired and replaced with the Primarily Virtual and Primarily Classroom values beginning with the 2016–17 school year.'));
COMMENT ON COLUMN schools.Magnet IS 'This field identifies whether a school is a magnet school and/or provides a magnet program.';
ALTER TABLE schools MODIFY (Magnet ANNOTATIONS (ADD value_description 'The field is coded as follows:· 1 = Magnet - The school is a magnet school and/or offers a magnet program.· 0 = Not Magnet - The school is not a magnet school and/or does not offer a magnet program.commonsense evidence:Note: Preschools and adult education centers do not contain a magnet school indicator.'));
COMMENT ON COLUMN schools.Latitude IS 'The angular distance (expressed in degrees) between the location of the school, district, or administrative authority and the equator measured north to south.';
ALTER TABLE schools MODIFY (Latitude ANNOTATIONS (ADD value_description 'The angular distance (expressed in degrees) between the location of the school, district, or administrative authority and the equator measured north to south.'));
COMMENT ON COLUMN schools.Longitude IS 'The angular distance (expressed in degrees) between the location of the school, district, or administrative authority and the prime meridian (Greenwich, England) measured from west to east.';
ALTER TABLE schools MODIFY (Longitude ANNOTATIONS (ADD value_description 'The angular distance (expressed in degrees) between the location of the school, district, or administrative authority and the prime meridian (Greenwich, England) measured from west to east.'));
COMMENT ON COLUMN schools.AdmFName1 IS 'administrator''s first name';
ALTER TABLE schools MODIFY (AdmFName1 ANNOTATIONS (ADD value_description 'The superintendent’s or principal’s first name.commonsense evidence:Only active and pending districts and schools will display administrator information, if applicable.'));
COMMENT ON COLUMN schools.AdmLName1 IS 'administrator''s last name';
ALTER TABLE schools MODIFY (AdmLName1 ANNOTATIONS (ADD value_description 'The superintendent’s or principal’s last name.commonsense evidence:Only active and pending districts and schools will display administrator information, if applicable.'));
COMMENT ON COLUMN schools.AdmEmail1 IS 'administrator''s email address';
ALTER TABLE schools MODIFY (AdmEmail1 ANNOTATIONS (ADD value_description 'The superintendent’s or principal’s email address.commonsense evidence:Only active and pending districts and schools will display administrator information, if applicable.'));
ALTER TABLE schools MODIFY (AdmFName2 ANNOTATIONS (ADD value_description 'SAME as 1'));
ALTER TABLE schools MODIFY (AdmFName3 ANNOTATIONS (ADD value_description 'not useful'));
ALTER TABLE schools MODIFY (AdmLName3 ANNOTATIONS (ADD value_description 'not useful'));
ALTER TABLE schools MODIFY (AdmEmail3 ANNOTATIONS (ADD value_description 'not useful'));
ALTER TABLE schools MODIFY (LastUpdate ANNOTATIONS (ADD value_description 'when is this record updated last time'));
