CREATE TABLE Country
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR2(4000) UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE League
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    country_id NUMBER,
    "name" VARCHAR2(4000) UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE "Match"
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    country_id NUMBER,
    league_id NUMBER,
    season VARCHAR2(4000),
    stage NUMBER,
    "date" VARCHAR2(4000),
    match_api_id NUMBER UNIQUE,
    home_team_api_id NUMBER,
    away_team_api_id NUMBER,
    home_team_goal NUMBER,
    away_team_goal NUMBER,
    home_player_X1 NUMBER,
    home_player_X2 NUMBER,
    home_player_X3 NUMBER,
    home_player_X4 NUMBER,
    home_player_X5 NUMBER,
    home_player_X6 NUMBER,
    home_player_X7 NUMBER,
    home_player_X8 NUMBER,
    home_player_X9 NUMBER,
    home_player_X10 NUMBER,
    home_player_X11 NUMBER,
    away_player_X1 NUMBER,
    away_player_X2 NUMBER,
    away_player_X3 NUMBER,
    away_player_X4 NUMBER,
    away_player_X5 NUMBER,
    away_player_X6 NUMBER,
    away_player_X7 NUMBER,
    away_player_X8 NUMBER,
    away_player_X9 NUMBER,
    away_player_X10 NUMBER,
    away_player_X11 NUMBER,
    home_player_Y1 NUMBER,
    home_player_Y2 NUMBER,
    home_player_Y3 NUMBER,
    home_player_Y4 NUMBER,
    home_player_Y5 NUMBER,
    home_player_Y6 NUMBER,
    home_player_Y7 NUMBER,
    home_player_Y8 NUMBER,
    home_player_Y9 NUMBER,
    home_player_Y10 NUMBER,
    home_player_Y11 NUMBER,
    away_player_Y1 NUMBER,
    away_player_Y2 NUMBER,
    away_player_Y3 NUMBER,
    away_player_Y4 NUMBER,
    away_player_Y5 NUMBER,
    away_player_Y6 NUMBER,
    away_player_Y7 NUMBER,
    away_player_Y8 NUMBER,
    away_player_Y9 NUMBER,
    away_player_Y10 NUMBER,
    away_player_Y11 NUMBER,
    home_player_1 NUMBER,
    home_player_2 NUMBER,
    home_player_3 NUMBER,
    home_player_4 NUMBER,
    home_player_5 NUMBER,
    home_player_6 NUMBER,
    home_player_7 NUMBER,
    home_player_8 NUMBER,
    home_player_9 NUMBER,
    home_player_10 NUMBER,
    home_player_11 NUMBER,
    away_player_1 NUMBER,
    away_player_2 NUMBER,
    away_player_3 NUMBER,
    away_player_4 NUMBER,
    away_player_5 NUMBER,
    away_player_6 NUMBER,
    away_player_7 NUMBER,
    away_player_8 NUMBER,
    away_player_9 NUMBER,
    away_player_10 NUMBER,
    away_player_11 NUMBER,
    goal VARCHAR2(4000),
    shoton VARCHAR2(4000),
    shotoff VARCHAR2(4000),
    foulcommit VARCHAR2(4000),
    card VARCHAR2(4000),
    "cross" VARCHAR2(4000),
    corner VARCHAR2(4000),
    possession VARCHAR2(4000),
    B365H NUMBER,
    B365D NUMBER,
    B365A NUMBER,
    BWH NUMBER,
    BWD NUMBER,
    BWA NUMBER,
    IWH NUMBER,
    IWD NUMBER,
    IWA NUMBER,
    LBH NUMBER,
    LBD NUMBER,
    LBA NUMBER,
    PSH NUMBER,
    PSD NUMBER,
    PSA NUMBER,
    WHH NUMBER,
    WHD NUMBER,
    WHA NUMBER,
    SJH NUMBER,
    SJD NUMBER,
    SJA NUMBER,
    VCH NUMBER,
    VCD NUMBER,
    VCA NUMBER,
    GBH NUMBER,
    GBD NUMBER,
    GBA NUMBER,
    BSH NUMBER,
    BSD NUMBER,
    BSA NUMBER,
    PRIMARY KEY (id)
);

CREATE TABLE Player
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player_api_id NUMBER UNIQUE,
    player_name VARCHAR2(4000),
    player_fifa_api_id NUMBER UNIQUE,
    birthday VARCHAR2(4000),
    height NUMBER,
    weight NUMBER,
    PRIMARY KEY (id)
);

CREATE TABLE Player_Attributes
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player_fifa_api_id NUMBER,
    player_api_id NUMBER,
    "date" VARCHAR2(4000),
    overall_rating NUMBER,
    potential NUMBER,
    preferred_foot VARCHAR2(4000),
    attacking_work_rate VARCHAR2(4000),
    defensive_work_rate VARCHAR2(4000),
    crossing NUMBER,
    finishing NUMBER,
    heading_accuracy NUMBER,
    short_passing NUMBER,
    volleys NUMBER,
    dribbling NUMBER,
    curve NUMBER,
    free_kick_accuracy NUMBER,
    long_passing NUMBER,
    ball_control NUMBER,
    acceleration NUMBER,
    sprint_speed NUMBER,
    agility NUMBER,
    reactions NUMBER,
    balance NUMBER,
    shot_power NUMBER,
    jumping NUMBER,
    stamina NUMBER,
    strength NUMBER,
    long_shots NUMBER,
    aggression NUMBER,
    interceptions NUMBER,
    positioning NUMBER,
    vision NUMBER,
    penalties NUMBER,
    marking NUMBER,
    standing_tackle NUMBER,
    sliding_tackle NUMBER,
    gk_diving NUMBER,
    gk_handling NUMBER,
    gk_kicking NUMBER,
    gk_positioning NUMBER,
    gk_reflexes NUMBER,
    PRIMARY KEY (id)
);

CREATE TABLE Team
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    team_api_id NUMBER UNIQUE,
    team_fifa_api_id NUMBER,
    team_long_name VARCHAR2(4000),
    team_short_name VARCHAR2(4000),
    PRIMARY KEY (id)
);

CREATE TABLE Team_Attributes
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    team_fifa_api_id NUMBER,
    team_api_id NUMBER,
    "date" VARCHAR2(4000),
    buildUpPlaySpeed NUMBER,
    buildUpPlaySpeedClass VARCHAR2(4000),
    buildUpPlayDribbling NUMBER,
    buildUpPlayDribblingClass VARCHAR2(4000),
    buildUpPlayPassing NUMBER,
    buildUpPlayPassingClass VARCHAR2(4000),
    buildUpPlayPositioningClass VARCHAR2(4000),
    chanceCreationPassing NUMBER,
    chanceCreationPassingClass VARCHAR2(4000),
    chanceCreationCrossing NUMBER,
    chanceCreationCrossingClass VARCHAR2(4000),
    chanceCreationShooting NUMBER,
    chanceCreationShootingClass VARCHAR2(4000),
    chanceCreationPositioningClass VARCHAR2(4000),
    defencePressure NUMBER,
    defencePressureClass VARCHAR2(4000),
    defenceAggression NUMBER,
    defenceAggressionClass VARCHAR2(4000),
    defenceTeamWidth NUMBER,
    defenceTeamWidthClass VARCHAR2(4000),
    defenceDefenderLineClass VARCHAR2(4000),
    PRIMARY KEY (id)
);

ALTER TABLE League ADD CONSTRAINT FK_LEAGUE_1 FOREIGN KEY (country_id) REFERENCES country (id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_1 FOREIGN KEY (home_team_api_id) REFERENCES Team (team_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_2 FOREIGN KEY (away_team_api_id) REFERENCES Team (team_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_3 FOREIGN KEY (home_player_1) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_4 FOREIGN KEY (home_player_2) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_5 FOREIGN KEY (home_player_3) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_6 FOREIGN KEY (home_player_4) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_7 FOREIGN KEY (home_player_5) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_8 FOREIGN KEY (home_player_6) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_9 FOREIGN KEY (home_player_7) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_10 FOREIGN KEY (home_player_8) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_11 FOREIGN KEY (home_player_9) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_12 FOREIGN KEY (home_player_10) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_13 FOREIGN KEY (home_player_11) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_14 FOREIGN KEY (away_player_1) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_15 FOREIGN KEY (away_player_2) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_16 FOREIGN KEY (away_player_3) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_17 FOREIGN KEY (away_player_4) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_18 FOREIGN KEY (away_player_5) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_19 FOREIGN KEY (away_player_6) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_20 FOREIGN KEY (away_player_7) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_21 FOREIGN KEY (away_player_8) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_22 FOREIGN KEY (away_player_9) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_23 FOREIGN KEY (away_player_10) REFERENCES Player (player_api_id);
ALTER TABLE "Match" ADD CONSTRAINT FK_MATCH_24 FOREIGN KEY (away_player_11) REFERENCES Player (player_api_id);
ALTER TABLE Player_Attributes ADD CONSTRAINT FK_PLAYER_ATTRIBUTES_1 FOREIGN KEY (player_fifa_api_id) REFERENCES Player (player_fifa_api_id);
ALTER TABLE Player_Attributes ADD CONSTRAINT FK_PLAYER_ATTRIBUTES_2 FOREIGN KEY (player_api_id) REFERENCES Player (player_api_id);
ALTER TABLE Team_Attributes ADD CONSTRAINT FK_TEAM_ATTRIBUTES_1 FOREIGN KEY (team_fifa_api_id) REFERENCES Team (team_fifa_api_id);
ALTER TABLE Team_Attributes ADD CONSTRAINT FK_TEAM_ATTRIBUTES_2 FOREIGN KEY (team_api_id) REFERENCES Team (team_api_id);
