-- Oracle Metadata for european_football_2
-- Generated from BIRD benchmark database_description CSVs

-- Table: Country
COMMENT ON COLUMN Country.id IS 'the unique id for countries';
COMMENT ON COLUMN Country."name" IS 'country name';

-- Table: League
COMMENT ON COLUMN League.id IS 'the unique id for leagues';
COMMENT ON COLUMN League.country_id IS 'the unique id for countries';
COMMENT ON COLUMN League."name" IS 'league name';

-- Table: Match
COMMENT ON COLUMN Match.id IS 'the unique id for matches';
COMMENT ON COLUMN Match.country_id IS 'country id';
COMMENT ON COLUMN Match.league_id IS 'league id';
COMMENT ON COLUMN Match.season IS 'the season of the match';
COMMENT ON COLUMN Match.stage IS 'the stage of the match';
COMMENT ON COLUMN Match."date" IS 'the date of the match';
ALTER TABLE Match MODIFY ("date" ANNOTATIONS (ADD value_description 'e.g. 2008-08-17 00:00:00'));
COMMENT ON COLUMN Match.match_api_id IS 'the id of the match api';
COMMENT ON COLUMN Match.home_team_api_id IS 'the id of the home team api';
COMMENT ON COLUMN Match.away_team_api_id IS 'the id of the away team api';
COMMENT ON COLUMN Match.home_team_goal IS 'the goal of the home team';
COMMENT ON COLUMN Match.away_team_goal IS 'the goal of the away team';
COMMENT ON COLUMN Match.goal IS 'the goal of the match';
COMMENT ON COLUMN Match.shoton IS 'the shot on goal of the match';
ALTER TABLE Match MODIFY (shoton ANNOTATIONS (ADD value_description 'commonsense reasoning: A shot on goal is a shot that enters the goal or would have entered the goal if it had not been blocked by the goalkeeper or another defensive player.'));
COMMENT ON COLUMN Match.shotoff IS 'the shot off goal of the match, which is the opposite of shot on';
COMMENT ON COLUMN Match.foulcommit IS 'the fouls occurred in the match';
COMMENT ON COLUMN Match.card IS 'the cards given in the match';
COMMENT ON COLUMN Match."cross" IS 'Balls sent into the opposition team''s area from a wide position in the match';
COMMENT ON COLUMN Match.corner IS 'Ball goes out of play for a corner kick in the match';
COMMENT ON COLUMN Match.possession IS 'The duration from a player taking over the ball in the match';

-- Table: Player
COMMENT ON COLUMN Player.id IS 'the unique id for players';
COMMENT ON COLUMN Player.player_api_id IS 'the id of the player api';
COMMENT ON COLUMN Player.player_name IS 'player name';
COMMENT ON COLUMN Player.player_fifa_api_id IS 'the id of the player fifa api';
COMMENT ON COLUMN Player.birthday IS 'the player''s birthday';
ALTER TABLE Player MODIFY (birthday ANNOTATIONS (ADD value_description 'e.g. 1992-02-29 00:00:00 commonsense reasoning: Player A is older than player B means that A''s birthday is earlier than B''s'));
COMMENT ON COLUMN Player.height IS 'the player''s height';
COMMENT ON COLUMN Player.weight IS 'the player''s weight';

-- Table: Player_Attributes
COMMENT ON COLUMN Player_Attributes.id IS 'the unique id for players';
COMMENT ON COLUMN Player_Attributes.player_fifa_api_id IS 'the id of the player fifa api';
COMMENT ON COLUMN Player_Attributes.player_api_id IS 'the id of the player api';
COMMENT ON COLUMN Player_Attributes."date" IS 'date';
ALTER TABLE Player_Attributes MODIFY ("date" ANNOTATIONS (ADD value_description 'e.g. 2016-02-18 00:00:00'));
COMMENT ON COLUMN Player_Attributes.overall_rating IS 'the overall rating of the player';
ALTER TABLE Player_Attributes MODIFY (overall_rating ANNOTATIONS (ADD value_description 'commonsense reasoning: The rating is between 0-100 which is calculated by FIFA. Higher overall rating means the player has a stronger overall strength.'));
COMMENT ON COLUMN Player_Attributes.potential IS 'potential of the player';
ALTER TABLE Player_Attributes MODIFY (potential ANNOTATIONS (ADD value_description 'commonsense reasoning: The potential score is between 0-100 which is calculated by FIFA. Higher potential score means that the player has more potential'));
COMMENT ON COLUMN Player_Attributes.preferred_foot IS 'the player''s preferred foot when attacking';
ALTER TABLE Player_Attributes MODIFY (preferred_foot ANNOTATIONS (ADD value_description 'right/ left'));
COMMENT ON COLUMN Player_Attributes.attacking_work_rate IS 'the player''s attacking work rate';
ALTER TABLE Player_Attributes MODIFY (attacking_work_rate ANNOTATIONS (ADD value_description 'commonsense reasoning:  high: implies that the player is going to be in all of your attack moves medium: implies that the player will select the attack actions he will join in low: remain in his position while the team attacks'));
COMMENT ON COLUMN Player_Attributes.defensive_work_rate IS 'the player''s defensive work rate';
ALTER TABLE Player_Attributes MODIFY (defensive_work_rate ANNOTATIONS (ADD value_description 'commonsense reasoning:  high: remain in his position and defense while the team attacks  medium: implies that the player will select the defensive actions he will join in low: implies that the player is going to be in all of your attack moves instead of defensing'));
COMMENT ON COLUMN Player_Attributes.crossing IS 'the player''s crossing score';
ALTER TABLE Player_Attributes MODIFY (crossing ANNOTATIONS (ADD value_description 'commonsense reasoning: Cross is a long pass into the opponent''s goal towards the header of sixth-yard teammate. The crossing score is between 0-100 which measures the tendency/frequency of crosses in the box. Higher potential score means that the player performs better in crossing actions.'));
COMMENT ON COLUMN Player_Attributes.finishing IS 'the player''s finishing rate';
ALTER TABLE Player_Attributes MODIFY (finishing ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.heading_accuracy IS 'the player''s heading accuracy';
ALTER TABLE Player_Attributes MODIFY (heading_accuracy ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.short_passing IS 'the player''s short passing score';
ALTER TABLE Player_Attributes MODIFY (short_passing ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.volleys IS 'the player''s volley score';
ALTER TABLE Player_Attributes MODIFY (volleys ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.dribbling IS 'the player''s dribbling score';
ALTER TABLE Player_Attributes MODIFY (dribbling ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.curve IS 'the player''s curve score';
ALTER TABLE Player_Attributes MODIFY (curve ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.free_kick_accuracy IS 'the player''s free kick accuracy';
ALTER TABLE Player_Attributes MODIFY (free_kick_accuracy ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.long_passing IS 'the player''s long passing score';
ALTER TABLE Player_Attributes MODIFY (long_passing ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.ball_control IS 'the player''s ball control score';
ALTER TABLE Player_Attributes MODIFY (ball_control ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.acceleration IS 'the player''s acceleration score';
ALTER TABLE Player_Attributes MODIFY (acceleration ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.sprint_speed IS 'the player''s sprint speed';
ALTER TABLE Player_Attributes MODIFY (sprint_speed ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.agility IS 'the player''s agility';
ALTER TABLE Player_Attributes MODIFY (agility ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.reactions IS 'the player''s reactions score';
ALTER TABLE Player_Attributes MODIFY (reactions ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.balance IS 'the player''s balance score';
ALTER TABLE Player_Attributes MODIFY (balance ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.shot_power IS 'the player''s shot power';
ALTER TABLE Player_Attributes MODIFY (shot_power ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.jumping IS 'the player''s jumping score';
ALTER TABLE Player_Attributes MODIFY (jumping ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.stamina IS 'the player''s stamina score';
ALTER TABLE Player_Attributes MODIFY (stamina ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.strength IS 'the player''s strength score';
ALTER TABLE Player_Attributes MODIFY (strength ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.long_shots IS 'the player''s long shots score';
ALTER TABLE Player_Attributes MODIFY (long_shots ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.aggression IS 'the player''s aggression score';
ALTER TABLE Player_Attributes MODIFY (aggression ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.interceptions IS 'the player''s interceptions score';
ALTER TABLE Player_Attributes MODIFY (interceptions ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.positioning IS 'the player''s positioning score';
ALTER TABLE Player_Attributes MODIFY (positioning ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.vision IS 'the player''s vision score';
ALTER TABLE Player_Attributes MODIFY (vision ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.penalties IS 'the player''s penalties score';
ALTER TABLE Player_Attributes MODIFY (penalties ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.marking IS 'the player''s markingscore';
ALTER TABLE Player_Attributes MODIFY (marking ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.standing_tackle IS 'the player''s standing tackle score';
ALTER TABLE Player_Attributes MODIFY (standing_tackle ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.sliding_tackle IS 'the player''s sliding tackle score';
ALTER TABLE Player_Attributes MODIFY (sliding_tackle ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.gk_diving IS 'the player''s goalkeep diving score';
ALTER TABLE Player_Attributes MODIFY (gk_diving ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.gk_handling IS 'the player''s goalkeep diving score';
ALTER TABLE Player_Attributes MODIFY (gk_handling ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.gk_kicking IS 'the player''s goalkeep kicking score';
ALTER TABLE Player_Attributes MODIFY (gk_kicking ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.gk_positioning IS 'the player''s goalkeep positioning score';
ALTER TABLE Player_Attributes MODIFY (gk_positioning ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));
COMMENT ON COLUMN Player_Attributes.gk_reflexes IS 'the player''s goalkeep reflexes score';
ALTER TABLE Player_Attributes MODIFY (gk_reflexes ANNOTATIONS (ADD value_description '0-100 which is calculated by FIFA'));

-- Table: Team
COMMENT ON COLUMN Team.id IS 'the unique id for teams';
COMMENT ON COLUMN Team.team_api_id IS 'the id of the team api';
COMMENT ON COLUMN Team.team_fifa_api_id IS 'the id of the team fifa api';
COMMENT ON COLUMN Team.team_long_name IS 'the team''s long name';
COMMENT ON COLUMN Team.team_short_name IS 'the team''s short name';

-- Table: Team_Attributes
COMMENT ON COLUMN Team_Attributes.id IS 'the unique id for teams';
COMMENT ON COLUMN Team_Attributes.team_fifa_api_id IS 'the id of the team fifa api';
COMMENT ON COLUMN Team_Attributes.team_api_id IS 'the id of the team api';
COMMENT ON COLUMN Team_Attributes."date" IS 'Date';
ALTER TABLE Team_Attributes MODIFY ("date" ANNOTATIONS (ADD value_description 'e.g. 2010-02-22 00:00:00'));
COMMENT ON COLUMN Team_Attributes.buildUpPlaySpeed IS 'the speed in which attacks are put together';
ALTER TABLE Team_Attributes MODIFY (buildUpPlaySpeed ANNOTATIONS (ADD value_description 'the score which is between 1-00 to measure the team''s attack speed'));
COMMENT ON COLUMN Team_Attributes.buildUpPlaySpeedClass IS 'the speed class';
ALTER TABLE Team_Attributes MODIFY (buildUpPlaySpeedClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Slow: 1-33 Balanced: 34-66 Fast: 66-100'));
COMMENT ON COLUMN Team_Attributes.buildUpPlayDribbling IS 'the tendency/ frequency of dribbling';
COMMENT ON COLUMN Team_Attributes.buildUpPlayDribblingClass IS 'the dribbling class';
ALTER TABLE Team_Attributes MODIFY (buildUpPlayDribblingClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Little: 1-33 Normal: 34-66 Lots: 66-100'));
COMMENT ON COLUMN Team_Attributes.buildUpPlayPassing IS 'affects passing distance and support from teammates';
COMMENT ON COLUMN Team_Attributes.buildUpPlayPassingClass IS 'the passing class';
ALTER TABLE Team_Attributes MODIFY (buildUpPlayPassingClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Short: 1-33 Mixed: 34-66 Long: 66-100'));
COMMENT ON COLUMN Team_Attributes.buildUpPlayPositioningClass IS 'A team''s freedom of movement in the 1st two thirds of the pitch';
ALTER TABLE Team_Attributes MODIFY (buildUpPlayPositioningClass ANNOTATIONS (ADD value_description 'Organised / Free Form'));
COMMENT ON COLUMN Team_Attributes.chanceCreationPassing IS 'Amount of risk in pass decision and run support';
COMMENT ON COLUMN Team_Attributes.chanceCreationPassingClass IS 'the chance creation passing class';
ALTER TABLE Team_Attributes MODIFY (chanceCreationPassingClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Safe: 1-33 Normal: 34-66 Risky: 66-100'));
COMMENT ON COLUMN Team_Attributes.chanceCreationCrossing IS 'The tendency / frequency of crosses into the box';
COMMENT ON COLUMN Team_Attributes.chanceCreationCrossingClass IS 'the chance creation crossing class';
ALTER TABLE Team_Attributes MODIFY (chanceCreationCrossingClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Little: 1-33 Normal: 34-66 Lots: 66-100'));
COMMENT ON COLUMN Team_Attributes.chanceCreationShooting IS 'The tendency / frequency of shots taken';
COMMENT ON COLUMN Team_Attributes.chanceCreationShootingClass IS 'the chance creation shooting class';
ALTER TABLE Team_Attributes MODIFY (chanceCreationShootingClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Little: 1-33 Normal: 34-66 Lots: 66-100'));
COMMENT ON COLUMN Team_Attributes.chanceCreationPositioningClass IS 'A teams freedom of movement in the final third of the pitch';
ALTER TABLE Team_Attributes MODIFY (chanceCreationPositioningClass ANNOTATIONS (ADD value_description 'Organised / Free Form'));
COMMENT ON COLUMN Team_Attributes.defencePressure IS 'Affects how high up the pitch the team will start pressuring';
COMMENT ON COLUMN Team_Attributes.defencePressureClass IS 'the defence pressure class';
ALTER TABLE Team_Attributes MODIFY (defencePressureClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Deep: 1-33 Medium: 34-66 High: 66-100'));
COMMENT ON COLUMN Team_Attributes.defenceAggression IS 'Affect the teams approach to tackling the ball possessor';
COMMENT ON COLUMN Team_Attributes.defenceAggressionClass IS 'the defence aggression class';
ALTER TABLE Team_Attributes MODIFY (defenceAggressionClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Contain: 1-33 Press: 34-66 Double: 66-100'));
COMMENT ON COLUMN Team_Attributes.defenceTeamWidth IS 'Affects how much the team will shift to the ball side';
COMMENT ON COLUMN Team_Attributes.defenceTeamWidthClass IS 'the defence team width class';
ALTER TABLE Team_Attributes MODIFY (defenceTeamWidthClass ANNOTATIONS (ADD value_description 'commonsense reasoning:  Narrow: 1-33 Normal: 34-66 Wide: 66-100'));
COMMENT ON COLUMN Team_Attributes.defenceDefenderLineClass IS 'Affects the shape and strategy of the defence';
ALTER TABLE Team_Attributes MODIFY (defenceDefenderLineClass ANNOTATIONS (ADD value_description 'Cover/ Offside Trap'));
